var $document=$(document),ua=navigator.userAgent.toLowerCase(),isWeixin=-1!=ua.indexOf("micromessenger"),isAndroid=-1!=ua.indexOf("android"),isIos=-1!=ua.indexOf("iphone")||-1!=ua.indexOf("ipad"),this_url=location.href,protocol=window.location.protocol,nowLocation=window.location.protocol+"//"+window.location.host,facepng=protocol+"//media.zmpal.com/zmpal/image/common/face.png",logoimg=protocol+"//media.zmpal.com/zmpal/image/common/qmjs_logo.jpg",gotopay="subscribe!wxauth.jsp",shareNum_link=nowLocation+
"/h5/share_tip.html",noData='<div style="text-align: center;padding: 1rem 0;color: #aaa;font-size: .7rem;" class="noData">\u6682\u65e0\u6570\u636e...</div>',random=Math.random(),document_title_js="document_title.js?v="+random,upload_img_js="upload_img.js?v="+random,wx_upload_img_js="wx_upload_img.js?v="+random,city_picker_js="//media.zmpal.com/zmpal/js/sm-city-picker.min.js",swiper_js="//media.zmpal.com/zmpal/js/swiper3.min.js",sm_extend_js="//media.zmpal.com/zmpal/js/sm-extend.min.js",qrcode_js=
"//media.zmpal.com/zmpal/js/qrcode.js",echarts_js="//media.zmpal.com/zmpal/js/echarts.min.js";window.parent!=window&&-1==document.referrer.indexOf("yuanwen")&&(window.parent.location.href=location.href);function getQueryString(a){a=new RegExp("(^|&|&amp;)"+a+"=([^&]*)(&|$)","i");a=window.location.search.substr(1).match(a);return null!=a?unescape(a[2]):null}function isphone(a){var b=0;a=$.trim(a);/^1[0-9]{10}$/.test(a)&&(b=1);return b}
function isnumber(a){var b=0;a=trim(a);/^[0-9]*$/.test(a)&&(b=1);return b}function ispw(a){var b=0;a=$.trim(a);/^[a-zA-Z0-9]{6,20}$/.test(a)&&(b=1);return b}function ismyname(a){var b=0;a=$.trim(a);var c=/^[\u4e00-\u9fa5a-zA-Z0-9]+$/;1<=a.length&&c.test(a)&&(b=1);return b}function isZZ(a){var b=0;/^\+?[1-9][0-9]*$/.test(a)&&(b=1);return b}function isemail(a){var b=0;/\w@\w*\.\w/.test(a)&&(b=1);return b}function trim(a){return a.replace(/(^\s*)|(\s*$)/g,"")}
function ltrim(a){return a.replace(/(^\s*)/g,"")}function rtrim(a){return a.replace(/(\s*$)/g,"")}function showloading(){$(".page-group").append('<div class="myloading">\r\n\t\t\t\t\t<div class="myloading_overlay"></div>\r\n\t\t\t\t\t<div class="myloading_modal">\r\n\t\t\t\t\t\t<span class="preloader preloader-white"></span>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>')}function hideloading(){$(".myloading").remove()}
function escape2Html(a){if(a&&"undefined"!=a){a=a.replace(/&amp;ldquo;/g,"\u201c").replace(/&amp;rdquo;/g,"\u201d").replace(/&ldquo;/g,"\u201c").replace(/&rdquo;/g,"\u201d").replace(/&lsquo;/g,"\u2018").replace(/&rsquo;/g,"\u2019").replace(/\(&quot;/g,"(").replace(/&quot;\)/g,")").replace(/&middot;/g,"\u00b7").replace(/&mdash;/g,"-").replace(/&amp;hellip;/g,"...").replace(/&hellip;/g,"...");var b={lt:"<",gt:">",nbsp:" ",amp:"&",quot:'"'};return a.replace(/&(lt|gt|nbsp|amp|quot);/ig,function(a,d){return b[d]})}return""}
function html2Escape(a){return a&&"undefined"!=a?a.replace(/[<>&"]/g,function(a){return{"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"}[a]}):""}function viewObj(a){if("object"!=typeof a)document.write(a+" ");else for(var b in a)document.write(b+":{"),viewObj(a[b]),document.write("}"),document.write("<br/>")}
var cookie=function(){return{getCookie:function(a){return(a=document.cookie.match(new RegExp("(?:^|; )"+a+"=([^;]*)")))?a[1]:null},setCookie:function(a,b,c){if(c){var d=new Date;d.setTime(parseFloat(+new Date)+6E4*c)}document.cookie=a+"="+b+"; "+(c?"expires="+d.toUTCString()+"; ":"")+"path=/;"},removeCookie:function(a){document.cookie=a+"=; expires=Mon, 2 Mar 2009 19:00:00 UTC; path=/;"}}}();clearCookie();
function clearCookie(){var a=document.cookie.split(";");if(20<a.length)for(var b in a){var c=a[b].split("=")[0];-1!=c.indexOf("_")&&(document.cookie=c+"=; expires=Mon, 2 Mar 2009 19:00:00 UTC; path=/;")}}function get_time(){var a=new Date,b=a.getFullYear(),c=a.getMonth()+1,a=a.getDate();return b=b+((10>c?"-0":"-")+c+"")+((10>a?"-0":"-")+a+"")}
function getthedate(a,b){a=parseISO8601(a);a=new Date(a);a=a.valueOf();a=new Date(a+864E5*b);b=a.getMonth()+1;1==b.toString().length&&(b="0"+b);var c=a.getDate();1==c.toString().length&&(c="0"+c);return a.getFullYear()+"-"+b+"-"+c}function parseISO8601(a){var b=new Date(NaN),c=/^\s*(\d{4})-(\d\d)-(\d\d)\s*$/.exec(a);c&&(a=+c[2],b.setFullYear(c[1],a-1,c[3]),a!=b.getMonth()+1&&b.setTime(NaN));return b}
function getDays(a,b){a=(new Date(Date.parse(a.replace(/-/g,"/")))).getTime();b=(new Date(Date.parse(b.replace(/-/g,"/")))).getTime();return Math.abs(a-b)/864E5}function audioAutoPlay(a){var b=document.getElementById(a),c=function(){b.play();document.removeEventListener("touchstart",c,!1)};b.play();wx.ready(function(){c()});document.addEventListener("touchstart",c,!1)}
$document.on("click",".vcard_kefu",function(){if(0<$(".kefu_pay").length){if(0>=$(".qrcode_menu_mask_contacts").length){var a='<div class="qrcode_menu_mask qrcode_menu_mask_contacts">\r\n\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_main">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_menu_close"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t<img src="" class="qrcode_menu_ewm" style="margin: 0;max-width: 100%;">\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>';$(".page-group").append(a)}$(".qrcode_menu_phone").hide();
$(".qrcode_menu_mask_contacts").show();$("#qrcodeWeixin").html("110633912");$(".qrcode_menu_ewm").attr("src","//media.zmpal.com/zmpal/image/common/paykf_gif2.png")}else 0>=$(".qrcode_menu_mask_contacts").length&&(a='<div class="qrcode_menu_mask qrcode_menu_mask_contacts">\r\n\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_main">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_info">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_weixin">\u5fae\u4fe1\u53f7\uff1a<span id="qrcodeWeixin"></span></div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_menu_close"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<img src="" class="qrcode_menu_ewm">\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>',
$(".page-group").append(a)),$(".qrcode_menu_phone").hide(),$(".qrcode_menu_mask_contacts").show(),$("#qrcodeWeixin").html("110309897"),$(".qrcode_menu_ewm").attr("src","//media.zmpal.com/zmpal/image/common/freekf_gif1.jpg")});$document.on("click",".qrcode_menu_close",function(){$(".qrcode_menu_mask").hide()});
function articleFixPage(a,b){var c=$(".article_content");a=a.replace(/!important/g,"").replace(/! important/g,"").replace(/ src/g," data-realsrc");if(0<$("#article-detail").length||0<$("#company-detail").length)a='<img src="//media.zmpal.com/zmpal/image/common/guide_head.gif" class="guide_head">'+a;0<$("#company-detail").length&&"product"!=b&&(a+='<img data-realsrc="//media.zmpal.com/zmpal/image/common/guide_foot2.gif" class="guide_foot">');if(0<$("#article-detail").length||0<$("#company-detail").length||
0<$("#article-view").length)a+='<div class="article_copyright">\u7248\u6743\u58f0\u660e\uff1a\u611f\u8c22\u539f\u4f5c\u8005\u7684\u8f9b\u82e6\u521b\u4f5c\uff0c\u5982\u8f6c\u8f7d\u6d89\u53ca\u7248\u6743\u7b49\u95ee\u9898\uff0c\u8bf7\u4e0e\u6211\u4eec\u8054\u7cfb\u5904\u7406\uff01</div>';c.html(a);0<$("#article-view").length?(a="",0<$(".article_content img").eq(0).length&&(a='<div style="text-align: center;"><img src="'+$(".article_content img").eq(0).attr("data-realsrc")+'"><div>'),$(".article_content img").remove(),
c.prepend(a)):$(".article_content img").picLazyLoad({threshold:400});$(".article_content iframe").each(function(){var a=$(this);a.attr("src",a.attr("data-realsrc"));a.removeAttr("data-realsrc")});c=document.body.offsetWidth-30;a=document.getElementsByTagName("iframe");for(var d in a){var f=b=0,e=a[d].src;if(!e)break;0<e.indexOf("preview")&&(e=e.replace("preview","player"));a[d].src=e;var h=e.split("&"),k;for(k in h){var g=h[k].split("=");if("width"==g[0]||-1!=g[0].indexOf("?width"))b=$.trim(g[1]);
else if("height"==g[0]||-1!=g[0].indexOf("?height"))f=$.trim(g[1]);if(0<b||0<f)e=e.replace("width="+b,"width="+c),e=e.replace("height="+f,"height="+parseInt(3*c/4)),a[d].src=e,a[d].width="100%",a[d].height=parseInt(3*c/4)}}$(".article_content *").css({"max-width":"100%"});$(".article_content img").css({height:"auto"});$(".article_content img").parent().css({"text-indent":"0"});$(".article_content table").css({width:"100%"});$(".article_content pre").css({"white-space":"normal"});$(".article_content iframe").css({width:"100%",
height:parseInt(3*c/4),border:"0","background-image":"",display:"block"})}$document.on("click","#seepwd",function(){var a=$(this),b=a.parent().find("input");a.hasClass("on")?(a.removeClass("on"),b.attr("type","password")):(a.addClass("on"),b.attr("type","text"))});$document.on("click",".openPhone",function(){location.href="tel:"+$(this).data("src")});$document.on("click","#qrcodePhone, .ftcard_phone",function(){location.href="tel:"+$(this).html()});
$document.on("click",".prolist_kefu, .openWeixin, #detailKefu, #pdetail_dianzhu, .ftcard_qrcode",function(){var a=$(this),b=a.data("src"),c=a.data("weixin"),d=a.data("phone"),f=a.data("iscert"),e=a.data("ispay"),a=a.data("comp");if("yes"==e){if(0>=$(".qrcode_menu_shiming").length)var h='<div class="qrcode_menu_mask qrcode_menu_shiming '+("yes"==f?"yes":"")+'">\r\n\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_main">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_shiming_comp overhidden1">\u516c\u53f8\uff1a<span id="qrcodeComp"></span></div>\r\n\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_menu_close"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_shiming_number qrcode_shiming_weixin">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_shiming_numberspan qrcode_shiming_weixinspan">\u5fae\u4fe1\u53f7\uff1a<span id="qrcodeWeixin"></span></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_shiming_number qrcode_shiming_phone">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_shiming_numberspan qrcode_shiming_phonespan">\u624b\u673a\u53f7\uff1a<span id="qrcodePhone"></span></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<img class="qrcode_shiming_img">\r\n\t\t\t\t\t\t\t\t\t\t\t<img class="qrcode_shiming_king" src="//media.zmpal.com/zmpal/image/common/icon_king.gif">\r\n\t\t\t\t\t\t\t\t\t\t\t<img class="qrcode_shiming_vip" src="//media.zmpal.com/zmpal/image/common/pdetail_jinpai.png">\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>'}else 0>=
$(".qrcode_menu_mask_contacts").length&&(h='<div class="qrcode_menu_mask qrcode_menu_mask_contacts">\r\n\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_main">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_info">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_weixin">\u5fae\u4fe1\u53f7\uff1a<span id="qrcodeWeixin"></span></div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_phone">\u624b\u673a\u53f7\uff1a<span id="qrcodePhone"></span></div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<span class="qrcode_menu_close"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t<img src="" class="qrcode_menu_ewm">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class="qrcode_menu_savetips" style="text-align: center;">\u957f\u6309\u626b\u7801\u52a0\u597d\u53cb\u54a8\u8be2</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>');
$(".page-group").append(h);$(".qrcode_menu_weixin, .qrcode_menu_phone").show();$("#qrcodeWeixin").html(c);$("#qrcodePhone").html(d);$("#qrcodeComp").html(a);$(".qrcode_menu_ewm, .qrcode_shiming_img").attr("src",b);$(".qrcode_menu_mask_contacts, .qrcode_menu_shiming").show()});
function footcardFun(a,b,c){-1!=a.picUrl.indexOf("zmpal.com")&&-1==a.picUrl.indexOf("@")&&-1==a.picUrl.indexOf("?")&&(a.picUrl+="?x-oss-process=image/resize,w_200,h_200");"yes"==a.isPay?($(".ftcard_vip").removeClass("hidden"),"yes"==a.isCert?$(".ftcard_auth").html("\u5df2\u5b9e\u540d\u8ba4\u8bc1").addClass("on"):$(".ftcard_auth").html("\u672a\u5b9e\u540d\u8ba4\u8bc1")):(a.typeId="",a.big="no",$(".ftcard_auth").html("\u672a\u5b9e\u540d\u8ba4\u8bc1"),$(".footcard_foot").remove(),$(".footcard_body").addClass("footcard_body_free"));
$(".ftcard_face").attr("src",a.picUrl);$(".ftcard_name").html(a.name);$(".ftcard_position").html(a.position);$(".ftcard_companyName").html(a.companyName);$(".ftcard_wxNo").html(a.wxNo);$(".ftcard_phone").html(a.phone);$("#detailKefu, .ftcard_qrcode").attr({"data-phone":a.phone,"data-weixin":a.wxNo,"data-iscert":a.isCert,"data-ispay":a.isPay,"data-comp":a.companyName,"data-src":a.wxPicCode});$(".ftcard_big_qrcode").attr({src:a.wxPicCode});cardInfo.cid==b&&($(".footcard_change").removeClass("hidden"),
$(".footcard_content").removeClass("footcard_content_visitor"));a.companyId&&("yes"==a.big||a.cardbglist)&&"no"==a.isHidden?$.ajax({type:"post",url:"/page/zmpal/companyshare!getCompanyById.jsp",data:{companyId:a.companyId},success:function(b){"success"==b.result?$(".ftcard_big_companyLogo").attr("src",b.logo+"?x-oss-process=image/resize,w_50").show():$(".ftcard_big_companyName").html(a.companyName)}}):$(".ftcard_big_companyName").html(a.companyName);if(!a.cardbglist){"no"==a.isHidden?$(".article_bottomad").show():
(0==$(".swiper-slide").length&&$(".vedit_product").remove(),$(".article_bottomad").html("").show(),$(".footcard_content, .footcard_change").remove());a.typeId?($(".footcard_"+a.big).attr("style","background: url("+a.background+") no-repeat;background-size: 100% 100%;"),$(".footcard_"+a.big).removeClass("hidden")):(a.big="no",a.cardbg||(a.cardbg="//media.zmpal.com/zmpal/cardbg/small_free_02.png"),$(".footcard_no").attr("style","background: url("+a.cardbg+") no-repeat;background-size: 100% 100%;"),
$(".footcard_no").removeClass("hidden"));$(".article_nickname").html(a.name).show();if(0<$("#article-view").length)$(".footcard_td3").remove();else $document.on("click",".article_bottomad_main, .footcard_body, .footcard_big_face, .footcard_big_weizhan",function(){0<$("#health-detail").length&&a.companyId?location.href="companyshare!index.jsp?userId="+a.userId:location.href="namecardshare!detail.jsp?cardId="+b});$document.on("click",".footcard_change",function(){location.href="namecard!type.jsp?type="+
c+"&big="+a.big});$("#detailReg").attr("href","register.jsp?sid="+a.userId);a.companyId?$("#detailWeb").attr("href","companyshare!index.jsp?userId="+a.userId):($("#detailWeb").remove(),$(".cardi_card").addClass("cardi_card_one"))}}
function footcard_nocard_fun(){$(".article_bottomad").show();$(".footcard_nocard").show();$(".footcard_nocard_img").attr("src",$(".footcard_nocard_img").data("src"));$(".article_nickname").html("\u5168\u6c11\u5065\u5546").show();$(".registerBtn, .vcard_wxewm_main").hide()}
function tongjiFunction(a){var b=window.localStorage,c=a.source+"_"+a.type+"_"+a.sourceCid;b.getItem(c)||(1E3<b.length&&b.clear(),b.setItem(c,1),$.ajax({type:"post",url:"statisticshare!stat.jsp",data:a,success:function(a){},error:function(){hideloading()}}))}document.onselectstart=function(a){if(!isWeixin)return!1};
function getShareLink(a){var b=1;if(-1!=a.indexOf("?"))if(-1!=a.indexOf("v=")){var c=a.split("&"),d;for(d in c){var f=c[d].split("=");"v"==f[0]&&(b=2,a=a.replace("v="+$.trim(f[1]),"v="+b))}}else a+="&v="+b;else a+="?v="+b;return a}$document.on("click","a.back",function(){history.back()});
function weixin_share_fun(a){-1==a.imgUrl.indexOf("http")&&(a.imgUrl=protocol+a.imgUrl);-1!=a.link.indexOf("#")&&(a.link=a.link.split("#")[0]);wx.ready(function(){wx.onMenuShareAppMessage(a);wx.onMenuShareTimeline(a);wx.onMenuShareQZone(a);wx.onMenuShareQQ(a);wx.onMenuShareWeibo(a)})}function cardComplete(a){var b=9;a.intro||--b;a.picUrl||--b;a.wxPicCode||--b;a=(100*b/9).toFixed(0)+"%";$(".complete_body").css("width",a);$(".complete_number").html(a)};